// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitOfWorkDemo.Infrastructure;

#nullable disable

namespace PMS.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20231228165349_make nic nullable")]
    partial class makenicnullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PMS.Core.Models.DTO.GetEmployeeStatisticsDto", b =>
                {
                    b.Property<int>("ActiveEmployees")
                        .HasColumnType("int");

                    b.Property<int>("NewEmployeesThisWeek")
                        .HasColumnType("int");

                    b.Property<int>("NewEmployeesToday")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmployees")
                        .HasColumnType("int");

                    b.ToTable("GetEmployeeStatisticsDto");
                });

            modelBuilder.Entity("PMS.Core.Models.EmployeeMedicalRecordDetails", b =>
                {
                    b.Property<int>("EmployeeMedicalRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeMedicalRecordID"), 1L, 1);

                    b.Property<DateTime?>("AdmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BHTNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DailyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fiepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Investigations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeProfileID")
                        .HasColumnType("int");

                    b.Property<string>("Plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReasonID")
                        .HasColumnType("bigint");

                    b.Property<string>("SpecialRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeMedicalRecordID");

                    b.HasIndex("EmployeeProfileID");

                    b.HasIndex("ReasonID");

                    b.ToTable("EmployeeRecord");
                });

            modelBuilder.Entity("PMS.Core.Models.Reason", b =>
                {
                    b.Property<long>("ReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReasonID"), 1L, 1);

                    b.Property<string>("ReasonDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReasonID");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("PMS.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UnitOfWorkDemo.Core.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("insuranceInfomation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PMS.Core.Models.EmployeeMedicalRecordDetails", b =>
                {
                    b.HasOne("UnitOfWorkDemo.Core.Models.Employee", "EmployeeProfile")
                        .WithMany("EmployeeMedicalRecordDetails")
                        .HasForeignKey("EmployeeProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Core.Models.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonID");

                    b.Navigation("EmployeeProfile");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("UnitOfWorkDemo.Core.Models.Employee", b =>
                {
                    b.Navigation("EmployeeMedicalRecordDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
